-- Samaun starter catalogue. Images are local branded placeholders until real product photography is added.
INSERT OR IGNORE INTO categories(name,slug,description) VALUES
('Spices & Herbs','spices-herbs','Pahadi spices, seeds, herbs and tea blends');

INSERT OR IGNORE INTO products(name,slug,description,category_id,price,compare_price,stock,image_key,active,featured,tags) VALUES
('Mandua (Ragi) Atta – 1 kg','mandua-ragi-atta-1kg','Stone-ground finger millet flour inspired by traditional Uttarakhand kitchens.',(SELECT id FROM categories WHERE slug='food-pantry'),180,220,40,'/product-food.svg',1,1,'mandua,ragi,flour,uttarakhand,pahadi'),
('Jhangora (Barnyard Millet) – 1 kg','jhangora-barnyard-millet-1kg','A Himalayan millet traditionally enjoyed in Uttarakhand homes.',(SELECT id FROM categories WHERE slug='food-pantry'),220,260,35,'/product-food.svg',1,1,'jhangora,millet,grain,pahadi'),
('Himalayan Rajma – 500 g','himalayan-rajma-500g','Creamy red kidney beans selected for everyday Himalayan-style cooking.',(SELECT id FROM categories WHERE slug='food-pantry'),260,300,30,'/product-food.svg',1,1,'rajma,beans,pahadi,uttarakhand'),
('Gahat Dal – 500 g','gahat-dal-500g','Traditional horse gram dal with a hearty, earthy character.',(SELECT id FROM categories WHERE slug='food-pantry'),210,240,30,'/product-food.svg',1,0,'gahat,dal,pulse,pahadi'),
('Kala Bhatt – 500 g','kala-bhatt-500g','Black soybean from the Himalayan pantry, suited to dals and local recipes.',(SELECT id FROM categories WHERE slug='food-pantry'),230,270,30,'/product-food.svg',1,0,'kala bhatt,soybean,pahadi'),
('Himalayan Honey – 250 g','himalayan-honey-250g','Small-batch style honey concept for the Samaun pantry collection.',(SELECT id FROM categories WHERE slug='food-pantry'),320,380,20,'/product-food.svg',1,0,'honey,natural,himalayan'),
('Pahadi Namak – 200 g','pahadi-namak-200g','A simple everyday pantry essential inspired by Uttarakhand kitchens.',(SELECT id FROM categories WHERE slug='food-pantry'),90,120,45,'/product-food.svg',1,0,'salt,pahadi,pantry'),
('Timur Pepper – 50 g','timur-pepper-50g','Aromatic Himalayan pepper with a bright, distinctive character.',(SELECT id FROM categories WHERE slug='spices-herbs'),160,190,35,'/product-spice.svg',1,1,'timur,pepper,spice,pahadi'),
('Bhang Seeds – 100 g','bhang-seeds-100g','Traditional Uttarakhand ingredient for chutneys and local recipes.',(SELECT id FROM categories WHERE slug='spices-herbs'),140,170,35,'/product-spice.svg',1,0,'bhang seeds,chutney,uttarakhand'),
('Jambu Herb – 25 g','jambu-herb-25g','A fragrant mountain herb traditionally used in regional cooking.',(SELECT id FROM categories WHERE slug='spices-herbs'),130,160,25,'/product-spice.svg',1,0,'jambu,herb,pahadi'),
('Buransh Herbal Tea – 20 sachets','buransh-herbal-tea-20','A floral tea concept inspired by Uttarakhand’s rhododendron landscape.',(SELECT id FROM categories WHERE slug='spices-herbs'),280,320,30,'/product-spice.svg',1,1,'buransh,tea,herbal,himalayan'),
('Himalayan Herbal Tea Blend – 50 g','himalayan-herbal-tea-50g','A soothing mountain-inspired tea blend for slow evenings.',(SELECT id FROM categories WHERE slug='spices-herbs'),240,280,30,'/product-spice.svg',1,0,'tea,herbal,himalayan'),
('Hemp Seed Oil – 100 ml','hemp-seed-oil-100ml','A premium wellness concept built around Himalayan hemp seeds.',(SELECT id FROM categories WHERE slug='wellness'),420,480,18,'/product-wellness.svg',1,1,'hemp oil,wellness,himalayan'),
('Apricot Kernel Oil – 100 ml','apricot-kernel-oil-100ml','Light botanical oil inspired by Himalayan apricot traditions.',(SELECT id FROM categories WHERE slug='wellness'),360,420,20,'/product-wellness.svg',1,0,'apricot oil,wellness,skin'),
('Nettle Herbal Tea – 40 g','nettle-herbal-tea-40g','A mountain herb tea concept for the everyday wellness shelf.',(SELECT id FROM categories WHERE slug='wellness'),220,260,25,'/product-wellness.svg',1,0,'nettle,tea,wellness'),
('Ringaal Basket – Small','ringaal-basket-small','Handmade-style bamboo craft concept inspired by Uttarakhand weaving traditions.',(SELECT id FROM categories WHERE slug='handicrafts'),650,750,8,'/product-craft.svg',1,1,'ringaal,bamboo,handmade,craft'),
('Handwoven Wool Pouch','handwoven-wool-pouch','A compact textile piece inspired by Himalayan wool craft.',(SELECT id FROM categories WHERE slug='handicrafts'),480,550,12,'/product-craft.svg',1,0,'wool,handwoven,craft'),
('Himalayan Wooden Serving Tray','himalayan-wooden-serving-tray','A simple serving piece designed around a warm Himalayan home aesthetic.',(SELECT id FROM categories WHERE slug='home-living'),850,990,7,'/product-home.svg',1,1,'wood,home,serving,handmade'),
('Copper Tumbler – 1 pc','copper-tumbler-1pc','A classic utility piece for a thoughtfully styled home.',(SELECT id FROM categories WHERE slug='home-living'),520,600,15,'/product-home.svg',1,0,'copper,home,utility'),
('Samaun Welcome Gift Box','samaun-welcome-gift-box','A curated starter box concept combining pantry favourites from the mountains.',(SELECT id FROM categories WHERE slug='gifts'),999,1199,10,'/product-gift.svg',1,1,'gift box,samaun,gifting,himalayan'),
('Pahadi Pantry Gift Box','pahadi-pantry-gift-box','A festive-style selection of grains, spices and pantry favourites.',(SELECT id FROM categories WHERE slug='gifts'),1299,1499,10,'/product-gift.svg',1,0,'gift,pahadi,food,hamper'),
('Himalayan Wellness Gift Box','himalayan-wellness-gift-box','A thoughtful wellness-themed gift selection inspired by mountain botanicals.',(SELECT id FROM categories WHERE slug='gifts'),1499,1699,8,'/product-gift.svg',1,0,'gift,wellness,hamper,himalayan');
