const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8', ...headers}});
const cors = {'access-control-allow-origin':'*','access-control-allow-headers':'Content-Type','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'};
const withCors = (r)=>{ const h=new Headers(r.headers); Object.entries(cors).forEach(([k,v])=>h.set(k,v)); return new Response(r.body,{status:r.status,headers:h}); };
const slugify = s => String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const cookie = (name, value, maxAge=86400) => `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;

async function sign(value, secret){ const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)); return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
const b64u = s => btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromB64u = s => { s=s.replace(/-/g,'+').replace(/_/g,'/'); while(s.length%4) s+='='; return atob(s); };
async function auth(request, env){
  let token='';
  const a=request.headers.get('Authorization')||'';
  if(a.startsWith('Bearer ')) token=a.slice(7).trim();
  if(!token){ const c=request.headers.get('Cookie')||''; const m=c.match(/samaun_admin=([^;]+)/); if(m) token=m[1]; }
  if(!token) return false;
  try {
    const [exp,sig]=fromB64u(token).split('.');
    if(!exp || !sig || Date.now()>Number(exp)) return false;
    const expected=await sign(exp,env.ADMIN_SESSION_SECRET||env.ADMIN_PASSWORD||'change-me');
    return sig===expected;
  } catch { return false; }
}
async function requireAuth(request, env){ if(!(await auth(request,env))) return json({error:'Unauthorized'},401,cors); return null; }
async function hashPassword(password, saltB64){ const salt=saltB64?Uint8Array.from(atob(saltB64),c=>c.charCodeAt(0)):crypto.getRandomValues(new Uint8Array(16)); const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256); return {salt:btoa(String.fromCharCode(...salt)),hash:btoa(String.fromCharCode(...new Uint8Array(bits)))}; }
async function customerFromRequest(request,env){ const c=request.headers.get('Cookie')||''; const m=c.match(/samaun_customer=([^;]+)/); if(!m) return null; try{const raw=fromB64u(m[1]); const [id,exp,sig]=raw.split('.'); if(!id||!exp||Date.now()>Number(exp)) return null; const expected=await sign(`${id}.${exp}`,env.CUSTOMER_SESSION_SECRET||env.ADMIN_SESSION_SECRET||'change-me'); if(sig!==expected) return null; const row=await env.DB.prepare('SELECT id,name,email,phone FROM customers WHERE id=? AND active=1').bind(Number(id)).first(); return row||null;}catch{return null;} }
async function requireCustomer(request,env){ const u=await customerFromRequest(request,env); return u||null; }
const customerCookie=(name,value,maxAge=604800)=>`${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;

function imgUrl(key){ return key ? (key.startsWith('/') ? key : `/api/image/${encodeURIComponent(key)}`) : '/placeholder.svg'; }

export async function onRequest(context){
  const {request,env}=context; if(request.method==='OPTIONS') return withCors(new Response(null,{status:204}));
  const url=new URL(request.url); const path=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean); const method=request.method;
  try {
    if(path[0]==='image' && path[1]){ const key=decodeURIComponent(path.slice(1).join('/')); const obj=await env.IMAGES.get(key); if(!obj) return new Response('Not found',{status:404}); const h=new Headers(); obj.writeHttpMetadata(h); h.set('cache-control','public, max-age=31536000, immutable'); return new Response(obj.body,{headers:h}); }
    if(path[0]==='auth' && path[1]==='login' && method==='POST'){
      const body=await request.json(); if(!env.ADMIN_PASSWORD) return json({error:'ADMIN_PASSWORD is not configured'},500,cors); if(body.password!==env.ADMIN_PASSWORD) return json({error:'Invalid password'},401,cors);
      const exp=Date.now()+86400000; const sig=await sign(String(exp),env.ADMIN_SESSION_SECRET||env.ADMIN_PASSWORD); const token=b64u(`${exp}.${sig}`); return withCors(json({ok:true,token},200,{'set-cookie':cookie('samaun_admin',token)}));
    }
    if(path[0]==='auth' && path[1]==='logout'){ return json({ok:true},200,{...cors,'set-cookie':cookie('samaun_admin','',0)}); }
    if(path[0]==='auth' && path[1]==='customer' && path[2]==='register' && method==='POST'){
      const b=await request.json(); if(!b.name||!b.email||!b.password) return withCors(json({error:'Name, email and password are required'},400)); if(String(b.password).length<8) return withCors(json({error:'Password must be at least 8 characters'},400)); const email=String(b.email).trim().toLowerCase(); const exists=await env.DB.prepare('SELECT id FROM customers WHERE email=?').bind(email).first(); if(exists) return withCors(json({error:'An account with this email already exists'},409)); const hp=await hashPassword(String(b.password)); const r=await env.DB.prepare('INSERT INTO customers(name,email,phone,password_hash,password_salt) VALUES(?,?,?,?,?)').bind(String(b.name).trim(),email,String(b.phone||'').trim(),hp.hash,hp.salt).run(); const id=r.meta.last_row_id,exp=Date.now()+604800000,sig=await sign(`${id}.${exp}`,env.CUSTOMER_SESSION_SECRET||env.ADMIN_SESSION_SECRET||'change-me'),token=b64u(`${id}.${exp}.${sig}`); const customer={id,name:String(b.name).trim(),email,phone:String(b.phone||'').trim()}; return withCors(json({ok:true,customer},201,{...cors,'set-cookie':customerCookie('samaun_customer',token)}));
    }
    if(path[0]==='auth' && path[1]==='customer' && path[2]==='login' && method==='POST'){
      const b=await request.json(); const email=String(b.email||'').trim().toLowerCase(); const row=await env.DB.prepare('SELECT * FROM customers WHERE email=? AND active=1').bind(email).first(); if(!row) return withCors(json({error:'Invalid email or password'},401)); const hp=await hashPassword(String(b.password||''),row.password_salt); if(hp.hash!==row.password_hash) return withCors(json({error:'Invalid email or password'},401)); const exp=Date.now()+604800000,sig=await sign(`${row.id}.${exp}`,env.CUSTOMER_SESSION_SECRET||env.ADMIN_SESSION_SECRET||'change-me'),token=b64u(`${row.id}.${exp}.${sig}`); const customer={id:row.id,name:row.name,email:row.email,phone:row.phone}; return withCors(json({ok:true,customer},200,{...cors,'set-cookie':customerCookie('samaun_customer',token)}));
    }
    if(path[0]==='auth' && path[1]==='customer' && path[2]==='me' && method==='GET'){ const customer=await customerFromRequest(request,env); if(!customer) return withCors(json({error:'Unauthorized'},401)); const orders=await env.DB.prepare('SELECT id,order_number,total,payment_status,order_status,created_at,items_json FROM orders WHERE customer_id=? ORDER BY created_at DESC').bind(customer.id).all(); const purchased_product_ids=[...new Set(orders.results.filter(o=>String(o.payment_status||'').toLowerCase()==='paid').flatMap(o=>{try{return JSON.parse(o.items_json||'[]').map(i=>Number(i.productId)).filter(Boolean)}catch{return[]}}))]; return withCors(json({customer,orders:orders.results.map(({items_json,...o})=>o),purchased_product_ids})); }
    if(path[0]==='auth' && path[1]==='customer' && path[2]==='logout'){ return withCors(json({ok:true},200,{...cors,'set-cookie':customerCookie('samaun_customer','',0)})); }
    if(path[0]==='reviews' && method==='GET'){ const rows=await env.DB.prepare(`SELECT r.*,p.name product_name FROM reviews r LEFT JOIN products p ON p.id=r.product_id WHERE r.status='approved' ORDER BY r.created_at DESC LIMIT 50`).all(); return withCors(json(rows.results)); }
    if(path[0]==='reviews' && method==='POST'){ const customer=await requireCustomer(request,env); if(!customer) return withCors(json({error:'Please sign in to write a review'},401)); const b=await request.json(); const productId=Number(b.product_id),rating=Math.min(5,Math.max(1,Number(b.rating)||5)); if(!productId||!String(b.body||'').trim()) return withCors(json({error:'Product and review text are required'},400)); const product=await env.DB.prepare('SELECT id FROM products WHERE id=? AND active=1').bind(productId).first(); if(!product) return withCors(json({error:'Product not found'},404)); const paidOrders=await env.DB.prepare("SELECT items_json FROM orders WHERE customer_id=? AND LOWER(payment_status)='paid'").bind(customer.id).all(); let purchased=false; for(const o of paidOrders.results){try{const items=JSON.parse(o.items_json||'[]'); if(items.some(i=>Number(i.productId)===productId)){purchased=true;break}}catch{}} if(!purchased) return withCors(json({error:'You can review this product only after purchasing it and having the payment confirmed.'},403)); await env.DB.prepare('INSERT INTO reviews(product_id,customer_id,rating,body,status,verified_purchase) VALUES(?,?,?,?,?,?)').bind(productId,customer.id,rating,String(b.body).trim(),'pending',1).run(); return withCors(json({ok:true},201)); }
    if(path[0]==='coupons' && path[1]==='validate' && method==='POST'){ const b=await request.json(); const code=String(b.code||'').trim().toUpperCase(); const subtotal=Number(b.subtotal)||0; const c=await env.DB.prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (starts_at IS NULL OR starts_at<=CURRENT_TIMESTAMP) AND (ends_at IS NULL OR ends_at>=CURRENT_TIMESTAMP)").bind(code).first(); if(!c) return withCors(json({error:'Invalid or expired offer code'},400)); if(subtotal<Number(c.min_order||0)) return withCors(json({error:`Minimum order value is ₹${Number(c.min_order||0).toLocaleString('en-IN')}`},400)); let discount=c.discount_type==='percent'?subtotal*Number(c.discount_value)/100:Number(c.discount_value); discount=Math.min(subtotal,discount,Number(c.max_discount||discount)); return withCors(json({ok:true,discount,message:c.discount_type==='percent'?`${c.discount_value}% offer applied`:`₹${c.discount_value} offer applied`})); }
    if(path[0]==='settings' && method==='GET'){ const rows=await env.DB.prepare('SELECT key,value FROM settings').all(); return withCors(json(Object.fromEntries(rows.results.map(r=>[r.key,r.value])))); }
    if(path[0]==='categories' && method==='GET'){ const rows=await env.DB.prepare('SELECT * FROM categories WHERE active=1 ORDER BY name').all(); return withCors(json(rows.results)); }
    if(path[0]==='products' && method==='GET'){
      const q=url.searchParams.get('q')||''; const category=url.searchParams.get('category')||''; let sql=`SELECT p.*, c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=1`; const args=[];
      if(q){sql+=' AND (p.name LIKE ? OR p.description LIKE ? OR p.tags LIKE ?)'; const x=`%${q}%`; args.push(x,x,x);} if(category){sql+=' AND c.slug=?'; args.push(category);} sql+=' ORDER BY p.featured DESC,p.created_at DESC'; const rows=await env.DB.prepare(sql).bind(...args).all(); return withCors(json(rows.results.map(p=>({...p,image:imgUrl(p.image_key),price:Number(p.price),compare_price:p.compare_price?Number(p.compare_price):null,stock:Number(p.stock),is_bestseller:String(p.tags||'').toLowerCase().split(',').map(x=>x.trim()).includes('bestseller'),is_premium:(p.category_name||'').toLowerCase()==='premium'||String(p.tags||'').toLowerCase().split(',').map(x=>x.trim()).includes('premium')}))));
    }
    if(path[0]==='orders' && path[1] && method==='PUT'){
      const b=await request.json(); if(!b.utr) return withCors(json({error:'UTR required'},400));
      await env.DB.prepare('UPDATE orders SET utr=?,updated_at=CURRENT_TIMESTAMP WHERE order_number=?').bind(String(b.utr).trim(),path[1]).run();
      return withCors(json({ok:true}));
    }
    if(path[0]==='orders' && method==='POST'){
      const b=await request.json(); if(!b.customer?.name||!b.customer?.phone||!b.customer?.address||!Array.isArray(b.items)||!b.items.length) return withCors(json({error:'Missing required order details'},400));
      // Accept the cart's current `id` field as well as the canonical `productId` field.
      // This keeps checkout compatible with existing carts created by the frontend.
      const productIdOf = i => Number(i.productId ?? i.product_id ?? i.id);
      const ids=b.items.map(productIdOf).filter(Boolean); if(!ids.length) return withCors(json({error:'No valid products in cart'},400));
      const placeholders=ids.map(()=>'?').join(','); const prod=await env.DB.prepare(`SELECT id,name,price,stock,image_key FROM products WHERE id IN (${placeholders}) AND active=1`).bind(...ids).all();
      const map=new Map(prod.results.map(p=>[Number(p.id),p]));
      let subtotal=0; const items=[]; for(const i of b.items){const productId=productIdOf(i); const p=map.get(productId); const qty=Math.max(1,Math.min(99,Number(i.qty)||1)); if(!p) continue; if(Number(p.stock)<qty) return withCors(json({error:`Insufficient stock for ${p.name}`},400)); subtotal+=Number(p.price)*qty; items.push({productId:p.id,name:p.name,price:Number(p.price),qty,image:imgUrl(p.image_key)});} if(!items.length) return withCors(json({error:'No valid products'},400));
      const customer=await customerFromRequest(request,env); let discount=0,couponCode=String(b.coupon_code||'').trim().toUpperCase(); if(couponCode){ const c=await env.DB.prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (starts_at IS NULL OR starts_at<=CURRENT_TIMESTAMP) AND (ends_at IS NULL OR ends_at>=CURRENT_TIMESTAMP)").bind(couponCode).first(); if(!c) return withCors(json({error:'Invalid or expired offer code'},400)); if(subtotal<Number(c.min_order||0)) return withCors(json({error:'Minimum order value not reached'},400)); discount=c.discount_type==='percent'?subtotal*Number(c.discount_value)/100:Number(c.discount_value); discount=Math.min(subtotal,discount,Number(c.max_discount||discount)); } const shipping=Number(b.shipping)||0,total=Math.max(0,subtotal-discount)+shipping, orderNumber=`SM${Date.now().toString().slice(-8)}`;
      await env.DB.prepare(`INSERT INTO orders(order_number,customer_id,customer_name,phone,email,address,city,state,pincode,items_json,subtotal,discount,coupon_code,shipping,total,payment_method) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(orderNumber,customer?.id||null,b.customer.name,b.customer.phone,b.customer.email||'',b.customer.address,b.customer.city||'',b.customer.state||'Uttarakhand',b.customer.pincode||'',JSON.stringify(items),subtotal,discount,couponCode||null,shipping,total,'UPI').run();
      for(const i of items) await env.DB.prepare('UPDATE products SET stock=stock-?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.qty,i.productId).run();
      return withCors(json({ok:true,orderNumber,total,discount,items},201));
    }
    const admin = path[0]==='admin';
    if(admin){ const denied=await requireAuth(request,env); if(denied) return withCors(denied); }
    if(admin && path[1]==='orders' && method==='GET'){ const rows=await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all(); return withCors(json(rows.results.map(o=>({...o,items:JSON.parse(o.items_json)})))); }
    if(admin && path[1]==='orders' && path[2] && method==='PUT'){ const id=Number(path[2]), b=await request.json(); const fields=[]; const vals=[]; for(const k of ['payment_status','order_status','utr']) if(b[k]!==undefined){fields.push(`${k}=?`);vals.push(b[k]);} fields.push('updated_at=CURRENT_TIMESTAMP'); await env.DB.prepare(`UPDATE orders SET ${fields.join(',')} WHERE id=?`).bind(...vals,id).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='products' && method==='GET'){ const rows=await env.DB.prepare('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.created_at DESC').all(); return withCors(json(rows.results.map(p=>({...p,image:imgUrl(p.image_key)})))); }
    if(admin && path[1]==='products' && method==='POST'){ const b=await request.json(); const slug=slugify(b.slug||b.name)+`-${Date.now().toString().slice(-5)}`; const r=await env.DB.prepare(`INSERT INTO products(name,slug,description,category_id,price,compare_price,stock,image_key,active,featured,tags) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(b.name,slug,b.description||'',b.category_id?Number(b.category_id):null,Math.round(Number(b.price)||0),b.compare_price?Math.round(Number(b.compare_price)):null,Math.max(0,Number(b.stock)||0),b.image_key||null,b.active===false?0:1,b.featured?1:0,b.tags||'').run(); return withCors(json({ok:true,id:r.meta.last_row_id},201)); }
    if(admin && path[1]==='products' && path[2] && method==='PUT'){ const id=Number(path[2]),b=await request.json(); await env.DB.prepare(`UPDATE products SET name=?,description=?,category_id=?,price=?,compare_price=?,stock=?,image_key=?,active=?,featured=?,tags=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.name,b.description||'',b.category_id?Number(b.category_id):null,Math.round(Number(b.price)||0),b.compare_price?Math.round(Number(b.compare_price)):null,Math.max(0,Number(b.stock)||0),b.image_key||null,b.active?1:0,b.featured?1:0,b.tags||'',id).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='products' && path[2] && method==='DELETE'){ await env.DB.prepare('DELETE FROM products WHERE id=?').bind(Number(path[2])).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='categories' && method==='POST'){ const b=await request.json(); await env.DB.prepare('INSERT INTO categories(name,slug,description) VALUES(?,?,?)').bind(b.name,slugify(b.name),b.description||'').run(); return withCors(json({ok:true},201)); }
    if(admin && path[1]==='settings' && method==='PUT'){ const b=await request.json(); for(const [k,v] of Object.entries(b)) await env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,String(v)).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='upload' && method==='POST'){ const form=await request.formData(); const file=form.get('file'); if(!file || typeof file.arrayBuffer!=='function') return withCors(json({error:'Image file required'},400)); if(file.size>5*1024*1024) return withCors(json({error:'Max image size is 5MB'},400)); const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,''); const key=`products/${crypto.randomUUID()}.${ext}`; await env.IMAGES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'image/jpeg'}}); return withCors(json({ok:true,key,url:imgUrl(key)})); }
    if(admin && path[1]==='reviews' && method==='GET'){ const rows=await env.DB.prepare(`SELECT r.*,p.name product_name,c.name customer_name,c.email FROM reviews r LEFT JOIN products p ON p.id=r.product_id LEFT JOIN customers c ON c.id=r.customer_id ORDER BY r.created_at DESC`).all(); return withCors(json(rows.results)); }
    if(admin && path[1]==='reviews' && path[2] && method==='PUT'){ const b=await request.json(); await env.DB.prepare('UPDATE reviews SET status=? WHERE id=?').bind(String(b.status||'pending'),Number(path[2])).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='reviews' && path[2] && method==='DELETE'){ await env.DB.prepare('DELETE FROM reviews WHERE id=?').bind(Number(path[2])).run(); return withCors(json({ok:true})); }
    if(admin && path[1]==='coupons' && method==='GET'){ const rows=await env.DB.prepare('SELECT * FROM coupons ORDER BY created_at DESC').all(); return withCors(json(rows.results)); }
    if(admin && path[1]==='coupons' && method==='POST'){ const b=await request.json(); const code=String(b.code||'').trim().toUpperCase(); if(!code) return withCors(json({error:'Coupon code required'},400)); await env.DB.prepare('INSERT INTO coupons(code,discount_type,discount_value,min_order,max_discount,active,starts_at,ends_at) VALUES(?,?,?,?,?,?,?,?)').bind(code,b.discount_type||'percent',Number(b.discount_value)||0,Number(b.min_order)||0,Number(b.max_discount)||0,b.active===false?0:1,b.starts_at||null,b.ends_at||null).run(); return withCors(json({ok:true},201)); }
    return withCors(json({error:'Not found'},404));
  } catch(e){ return withCors(json({error:e.message||'Server error'},500)); }
}
